---
- name: zypper update
  zypper: 
    name: "*"
    state: latest

- name: Remove docker engime if present
  zypper:
    name: docker
    state: absent

- name: Install docker from rancher script
  shell: |
    curl https://releases.rancher.com/install-docker/19.03.sh | sh

- name: Install docker from rancher script
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install k8s kubectl
  shell:
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod 755 kubectl
    mv kubectl /usr/local/bin/

- name: Download RKE binary
  shell: |
    curl -LO https://github.com/rancher/rke/releases/download/v1.1.19/rke_linux-amd64
    chmod 755 rke_linux-amd64
    mv rke_linux-adm64 /usr/local/bin/

- name: copy rke config.yml
  copy:
    src: files/config.yml
    dest: /root/config.yml
    owner: root
    group: root
    mode: '0644'

- name: RKE up
  shell: |
    rke up