---
- name: zypper update
  zypper: 
    name: "*"
    state: latest

- name: Install docker engime
  zypper:
    name: docker
    state: present

- name: enable systemd docker 
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install k8s kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod 755 kubectl
    mv kubectl /usr/local/bin/

- name: Download RKE binary
  shell: |
    curl -LO https://github.com/rancher/rke/releases/download/v1.1.19/rke_linux-amd64
    chmod 755 rke_linux-amd64
    mv rke_linux-amd64 /usr/local/bin/rke

- name: copy rke config.yml
  copy:
    src: files/cluster.yml
    dest: /home/ec2-user/cluster.yml
    owner: ec2-user
    group: users
    mode: '0644'

- name: create SSH RSA keys and add to authorized_keys
  shell: |
    ssh-keygen -f id_rsa -t rsa -N ''
    # cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys

- name: RKE up
  shell: |
    sudo rke 