---
- name: Def CRI-O modules
  shell: |
    cat <<EOF | tee /etc/modules-load.d/crio.conf
    overlay
    br_netfilter
    EOF
    modprobe overlay
    modprobe br_netfilter

- name: Def CRI-O network systemctl
  shell: |
    cat <<EOF | tee /etc/sysctl.d/99-kubernetes-cri.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.ipv4.ip_forward                 = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    EOF
    sysctl --system

- name: Install CRI-O binary and daemon
  shell: |
    export OS=Centos_8
    export VERSION=1.20
    curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo
    dnf install cri-o -y
    systemctl daemon-reload
    systemctl enable crio --now

- name: Install k8s dameon and binary
  shell: |
    cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled=1
    gpgcheck=1
    repo_gpgcheck=1
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude=kubelet kubeadm kubectl
    EOF
    sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
    dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

# - name: kubeadm init
#   shell: |
#     kubeadm init