apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfsshare/pv001
    server: 172.31.93.1
    readOnly: false
  persistentVolumeReclaimPolicy: Retain 
