apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: default-backup
  namespace: longhorn-system
spec:
  cron: "*/5 * * * *"
  task: "backup"
  groups:
  - default
  retain: 70
  concurrency: 50