apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web01
  name: web01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web01
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol01
          mountPath: /usr/share/nginx/html
        resources: {}
      volumes:
      - name: vol01
        configMap:
          name: web01-wwwdata
