# This is a basic workflow to help you get started with Actions

name: CDTerraform

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  flat:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Download Terraform
        run: |
              curl -sL https://releases.hashicorp.com/terraform/0.14.8/terraform_0.14.8_linux_amd64.zip -o tf.zip
              unzip tf.zip
              cp terraform lab/terraform/

      - name: show path dir
        run: pwd

      - name: list files
        run: ls -l
      
      - name: terraform-init
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
              cd lab/terraform
              ./terraform init -backend-config="access_key=$(echo $TF_VAR_AWS_ACCESS_KEY_ID)" -backend-config="secret_key=$(echo $TF_VAR_AWS_SECRET_ACCESS_KEY)"
        
      - name: terraform-plan
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AWS_KEY_SSH: ${{ secrets.AWS_KEY_SSH }}
        run: |
              cd lab/terraform
              ./terraform plan 

      - name: terraform-apply
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AWS_KEY_SSH: ${{ secrets.AWS_KEY_SSH }}
        run: |
              echo $TF_VAR_AWS_KEY_SSH > lab/terraform/file.pem
              chmod 600 lab/terraform/file.pem
              cd lab/terraform
              ./terraform apply -auto-approve
